workers_dir: ./workers
workers:
  defoult:
    iothreads: 1
    hosts: ['127.0.0.1']
    ports: [2203]
  test_worker:
    iothreads: 1
    hosts: ['127.0.0.1']
    ports: [2203]
broker:
  iothreads: 1
  frontend:
    hosts: ['127.0.0.1']
    ports: [<%= (2200..2202).to_a.join(', ') %>]
  backend:
    host: '127.0.0.1'
    port: 2203