development: &default
  workers_dir: ./examples/workers
  workers:
    default:
      iothreads: 1
      hosts: ['127.0.0.1']
      ports: [2203]
    test_worker:
      metric:
        period: 10
      iothreads: 1
      hosts: ['127.0.0.1']
      ports: [3131]
  broker:
    iothreads: 1
    frontend:
      hosts: ['127.0.0.1']
      ports: [<%= (2200..2202).to_a.join(', ') %>]
    backend:
      hosts: '127.0.0.1'
      ports: 2203
test:
  <<: *default
production:
  <<: *default
